<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
Layout::includeLayout('header'); ?>


<input type="hidden" name="page" value="home">
<script src="<?= Asset::js('/wobblyslideshoweffect/snap.svg-min.js')?>"></script>
<script src="<?= Asset::js('/wobblyslideshoweffect/modernizr.custom.js')?>"></script>
<script src="<?= Asset::js('/wobblyslideshoweffect/classie.js')?>"></script>
<script src="<?= Asset::js('/wobblyslideshoweffect/sliderFx.js')?>"></script>
<script src="<?= Asset::js('/bootstrap/bootstrap.bundle.min.js')?>"></script> 
<link rel="stylesheet" href="<?= Asset::css('/bootstrap/bootstrap.min.css')?>" media="screen" >
<link rel="stylesheet" href="<?= Asset::css('/wobblyslideshoweffect/normalize.css')?>" media="screen" >
<link rel="stylesheet" href="<?= Asset::css('/wobblyslideshoweffect/slideshow.css')?>" media="screen" >    


    <!-- container -->
    <div class="container-fluid">
	    <div id="main" class="container-fluid">
		
	    	<div id="slideshow" class="slideshow">
				<ul>
					<li>
						<div class="slide">
							<div class="row">
								<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
									<h2>Sign up and start playing now, it's completely free!</h2>
								</div>
							  	<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
							  		<img class="img-fluid" alt="Responsive image" src="<?= Asset::image('aces.jpg')?>">
							  	</div>
							  	<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
							  		<?php 
								  		if(Session::has('username'))
								  			echo "<button class='btn btn-outline-secondary my-2 my-lg-0 btn-lg' type='submit'><a href='". URL::toRoute('game/') ."'>Play</a></button>";
							  			else
							  				echo "<button id='showLogin' class='btn btn-outline-secondary my-2 my-lg-0 btn-lg' type='submit'>Register</button>";
							  		?>
							  	</div>
							</div>
						</div>
					</li>
					<li>
						<div class="slide">
							<div class="row">
								<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
									<h2>Try to hit the top 10 of the best bets in BlackJack. Believe me, it's not easy...</h2>
								</div>
							  	<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
							  		<img class="img-fluid" alt="Responsive image" src="<?= Asset::image('lucky.jpg')?>">
							  	</div>
							  	<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
							  		<button class='btn btn-outline-secondary my-2 my-lg-0 btn-lg' type='submit'><a href='<?=URL::toRoute('plano/index')?>'>Jacktop 10</a></button>
							  	</div>
							</div>
						</div>
					</li>
					<li>
						<div class="slide">
							<div class="row">
								<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
									<h2>You do not have credits? It does not matter! Just do not abuse Jack and get blocked!</h2>
								</div>
							  	<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
							  		<img class="img-fluid" alt="Responsive image" src="<?= Asset::image('chips.jpg')?>">
							  	</div>
							</div>
						</div>
					</li>					
					<li>
						<div class="slide">
							<div class="row">
								<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
									<h2>Why are you in this slider? Shouldn't you be playing?</h2>
								</div>
							  	<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
							  		<img class="img-fluid" alt="Responsive image" src="<?= Asset::image('dealer.jpg')?>">
							  	</div>
							  	<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
							  		<?php 
								  		if(Session::has('username'))
								  			echo "<button class='btn btn-outline-secondary my-2 my-lg-0 btn-lg' type='submit'><a href='". URL::toRoute('game/') ."'>PLAY !</a></button>";
							  			else
							  				echo "<button id='showLogin' class='btn btn-outline-secondary my-2 my-lg-0 btn-lg' type='submit'>Register !</button>";
							  		?>
							  	</div>
							  	<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
							  		<small style="font-size: 10px">Slider by Sergey Valiukh</small>
							  	</div>
							</div>
						</div>
					</li>
				</ul>
			</div>

		</div>
	</div>
    <!-- /container -->
    <script src="<?= Asset::js('/changeActiveNavLink.js')?>"></script>
    <script type="text/javascript">
    	(function() {
			new SliderFx( document.getElementById('slideshow'), {
				easing : 'cubic-bezier(.8,0,.2,1)'
			} );

			$(document).on("click", "#showLogin" , function() {
	            $('#modalLogin').modal('show');
	        });

	        if($( "#modalLogin" ).hasClass( "showing" )){
	        	$( "#modalLogin").modal('show');
	        }
		})();
    </script>
    
<?php Layout::includeLayout('footer'); ?>