<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('header'); ?>
<link rel="stylesheet" href="<?= Asset::css('/profile.css')?>" media="screen" >

	<input type="hidden" name="page" value="profile">
    <!-- container -->
    <div id="containerProfile" class="container">

    	<h2 style="color: white; padding-left: 20px; padding-top: 40px;">Profile</h2>

    	<ul class="list-group mx-auto">
		  	<li class="list-group-item list-group-item-secondary">
			  	<div class="d-flex w-100 justify-content-between">
			    	<strong class="mb-1">Username:</strong>
			      	<h6> <?php echo Data::get('currentUser')->username ?> </h6>
			      	<button type="button" disabled=""><i class="fas fa-edit"></i></button>
			    </div>
		    </li>
		    <li class="list-group-item list-group-item-secondary">
			  	<div class="d-flex w-100 justify-content-between">
			    	<strong class="mb-1">Full Name:</strong>
			      	<input <?php echo "value='".Data::get('currentUser')->name."'"; ?> name="name" type="text" class="form-control" placeholder="Enter your name" required="Insert your name" disabled>
			      	<button id="btnEditname" type="button"><i class="fas fa-edit"></i></button>
			    </div>
		    </li>
		    <li class="list-group-item list-group-item-secondary">
			  	<div class="d-flex w-100 justify-content-between">
			    	<strong class="mb-1">Email:</strong>
			      	<input <?php echo "value='".Data::get('currentUser')->email."'"; ?> name="email" type="email" class="form-control" placeholder="Enter email" required="Insert your email" disabled>
			      	<button id="btnEditemail" type="button"><i class="fas fa-edit"></i></button>
			    </div>
		    </li>
		    <li class="list-group-item list-group-item-secondary">
			  	<div class="d-flex w-100 justify-content-between">
			    	<strong class="mb-1">Birthdate:</strong>
			      	<input <?php echo "value='".Data::get('currentUser')->birthdate->format('Y-m-d')."'"; ?> name="birthdate" type="date" class="form-control" required="Insert your birthdate" disabled>
			      	<button id="btnEditbirthdate" type="button"><i class="fas fa-edit"></i></button>
			    </div>
		    </li>
		    <li class="list-group-item list-group-item-secondary">
			  	<div class="d-flex w-100 justify-content-between">
			    	<strong class="mb-1">Password:</strong>
			      	<input <?php echo "value='".Data::get('currentUser')->password."'"; ?> name="password" type="password" class="form-control" placeholder="Enter password" required="Insert your password" disabled>
			      	<div class="row">
			      		<div class="col"><button id="btnEditpassword" type="button"><i class="fas fa-edit"></i></button></div>
			      		<div class="col"><button id="btnViewPassword" type="button"><i class="fas fa-edit"></i></button></div>
			      	</div>
			    </div>
		    </li>
		</ul>

		<h2 style="color: white; padding-left: 20px;">Transactions</h2>

		<div id="creditSection" class="row mx-auto">
			<div class="col align-self-center"><h3>Credit: <?php echo Data::get('currentUser')->balance ?></h3></div>
  			<div class="col">
  				<div class="row"><input name="addCredit" placeholder="€ 0.00" min="0" step="0.01" title="Currency" type="number" class="form-control"></div>
  				<div style="margin-top: 7px;" class="row"><button type="button" class="btn btn-success btn-lg btn-block">Convert to credits (x4)</button></div>
  			</div>
    	</div>   


		<table class="table table-dark mx-auto">
			<thead>
		    	<tr>
		      		<th scope="col">#</th>
		      		<th scope="col">Date/Hour</th>
		      		<th scope="col">Type</th>
		      		<th scope="col">Description</th>
		      		<th scope="col">Credit</th>
		      		<th scope="col">Debit</th>
		      		<th scope="col">Balance</th>
		    	</tr>
		  	</thead>
		 	<tbody>
		    	<tr>
		      		<th scope="row">1</th>
		      		<td>Mark</td>
		      		<td>Otto</td>
		      		<td>@mdo</td>
		    	</tr>		    	
		 	</tbody>
		</table>

	</div>

    <script src="<?= Asset::js('/changeActiveNavLink.js')?>"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
    	(function() {
    		$( "#btnEditname" ).click(function() {
    			if($("input[name=name]").prop('disabled'))
    				$("input[name=name]").prop('disabled', false);
    			else{    				
    				$("input[name=name]").prop('disabled', true);    				
					var value = $('input[name=name]').val();

					//testar editar com o campo nome, depois tentar fazer dinamico para todos os campos
					$.ajax({url: "edit/", type: 'post', data:{name:value}, success: function(result){
				    	console.log(result);
				    }});
    			}
			});
		})();
    </script>
    
<?php Layout::includeLayout('footer'); ?>