<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
?>

<footer class="page-footer font-small blue pt-4 mt-4">

  	<div class="container-fluid text-center text-md-left">

    	<div class="row">

      		<div class="col-md-6 mt-md-0 mt-3">

        		<h5 class="text-uppercase"><img src="<?= Asset::image('icon.png')?>" width="30" height="30" class="d-inline-block align-top" alt=""> Jackblack</h5>
       			<p>Here you can bet every time you want too try to be in the JACKTOP 10! You just have to log in and start playing.</p>

      		</div>

      		<hr class="clearfix w-100 d-md-none pb-3">

      		<div class="col-md-6 mb-md-0 mb-3">

        		<h5 class="text-uppercase">Links</h5>

		        <ul class="list-unstyled">
			        <li>
			        	<a href="<?=URL::toRoute('home/')?>">Home</a>
			        </li>
			        <?php 
		      			if(Session::has('user'))
	      					echo "<li><a href='". URL::toRoute('plano/index') ."''>Profile</a></li>";
		      		?>
			        <li>
			            <a href="<?=URL::toRoute('plano/index')?>">Jacktop 10</a>
			        </li>
		        </ul>

     		</div>

    	</div>

  	</div>
  	<div class="footer-copyright text-center py-3">© 2018 Copyright: Afonso Pinheiro, Alexandre Rodrigues, João Fernandes PSI1</div>

</footer>

</body>
</html>