<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Layout;
if(!Session::has('username'))
  Layout::includeLayout('modalLogin');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1">
    <meta name="author"      content="Afonso Pinheiro, Alexandre Rodrigues, João Fernandes, TeSP PSI1">

    <title>BlackJack</title>

    <?=AssetBundler::css()?>
    <link rel="shortcut icon" href="<?= Asset::image('icon.png')?>">
    <link rel="stylesheet" href="<?= Asset::css('/main.css')?>" media="screen" >
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700"  media="screen">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">  
    
    <script src="<?= Asset::js('/jquery-3.3.1.min')?>"></script>
    <script src="<?= Asset::js('/bootstrap/bootstrap.min.js')?>"></script>       
</head>

<body style="background-image: url(<?php echo Asset::image('main-background.jpg') ?>); background-attachment: fixed;background-position: center;background-repeat: no-repeat;background-size: cover;">
    <!-- start navbar--> 
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="<?=URL::toRoute('home/')?>"><img src="<?= Asset::image('icon.png')?>" width="30" height="30" class="d-inline-block align-top" alt=""></a>
	  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    	<span class="navbar-toggler-icon"></span>
	  	</button>

	  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
	    	<ul class="navbar-nav mr-auto">
    			  <li id="navhome" class="nav-item">
	        		<a class="nav-link" href="<?=URL::toRoute('home/')?>">Home</a>
	      		</li>
	      		<?php 
	      			if(Session::has('username'))
      					echo "<li id='navprofile' class='nav-item'><a class='nav-link' href='". URL::toRoute('profile/') ."''>Profile</a></li>";
	      		?>
	      		<li id="navjacktop" class="nav-item">
	        		<a class="nav-link" href="<?=URL::toRoute('plano/index')?>">Jacktop 10</a>
      			</li>	
            <?php 
              if(Session::has('username')) 
                echo "<li style='padding-left: 30px;' id='navprofile' class='nav-item'><strong class='nav-link'>".Session::get('username')."</strong></li>";
            ?>
	    	</ul>
	    	<?php 
      			if(Session::has('username'))
  					  echo "<a class='btn btn-outline-secondary my-2 my-sm-0'href='". URL::toRoute('game/') ."'>Play</a>".
  					       "<a class='btn btn-link' href='". URL::toRoute('logout/') ."'> <i class='fas fa-power-off'></i></a>";
				    else
					    echo "<button style='cursor: pointer;' class='btn btn-outline-secondary my-2 my-sm-0 disabled' type='submit'>Play</button>".
                   "<a id='showLogin' class='btn btn-link'> <i class='fas fa-power-off'></i></a>";
      	?>  			 
	  	</div>
	</nav>
	<!-- end navbar--> 