<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Layout;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1">
    <meta name="author"      content="Afonso Pinheiro, Alexandre Rodrigues, João Fernandes, TeSP PSI1">

    <?=AssetBundler::css()?>
    <link rel="shortcut icon" href="<?= Asset::image('icon.png')?>">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700"  media="screen">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">  
    
    <script src="<?= Asset::js('/jquery-3.3.1.min')?>"></script>
    <script src="<?= Asset::js('/bootstrap/bootstrap.min.js')?>"></script>       
</head>

<body style="background-image: url(<?php echo Asset::image('main-background.jpg') ?>); background-attachment: fixed;background-position: center;background-repeat: no-repeat;background-size: cover;">
    <!-- start navbar--> 
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="<?=URL::toRoute('home/')?>"><img src="<?= Asset::image('icon.png')?>" width="30" height="30" class="d-inline-block align-top" alt=""></a>
	  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    	<span class="navbar-toggler-icon"></span>
	  	</button>

	  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
	    	<?php 
          if(Session::has('username')) 
            echo "<strong class='nav-link'>".Session::get('username')."</strong>";
        ?>
	    	<a class='btn btn-link' href="<?=URL::toRoute('logout/')?>"> <i class='fas fa-power-off'></i></a>
	  	</div>
	</nav>
	<!-- end navbar--> 