<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1">
    <meta name="author"      content="Afonso Pinheiro, Alexandre Rodrigues, João Fernandes, TeSP PSI1">

    <title>BlackJack</title>

    <?=AssetBundler::css()?>
    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png')?>">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700"  media="screen">
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap.min.css')?>" media="screen" >
    <script src="<?= Asset::js('/jquery-3.3.1.min')?>"></script>
    <script src="<?= Asset::js('/bootstrap.min.js')?>"></script>
</head>

<body>
    <!-- navbar--> 