<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\URL;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="author"      content="Afonso Pinheiro, Alexandre Rodrigues, João Fernandes, TeSP PSI1">

    <title>BlackJack</title>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png')?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css')?>" media="screen" >
</head>

<body>
    <!-- navbar--> 