<?php
  use ArmoredCore\WebObjects\Data;
?> 
<?php 
  if(Data::get('userNotFound') == null) 
    echo "<div class='modal fade hiding' id='modalLogin' tabindex='-1' role='dialog' aria-hidden='true'>"; 
  else 
    echo "<div class='modal fade showing' id='modalLogin' tabindex='-1' role='dialog' aria-hidden='true'>"; 
?>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Login / Register</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">


        <div id="accordion">
          <div class="card">
            <div class="card-header" id="headingOne">
              <h5 class="mb-0">
                <button class="btn btn-light" data-toggle="collapse" data-target="#collapseLogin" aria-expanded="true" aria-controls="collapseLogin">
                  Login
                </button>
              </h5>
            </div>
            <div id="collapseLogin" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
              <div class="card-body">


                <form action="login/" method="POST">
                  <div class="form-group">
                    <label>Email address</label>
                    <input <?php if(Data::get('userNotFound') != null) echo "value='".Data::get('userNotFound')->email."'"; ?> name="email" type="email" class="form-control" placeholder="Enter email" required="Insert your email">
                    <small id="emailHelp" class="form-text text-muted">Ex: example@gmail.com</small>
                  </div>
                  <div class="form-group">
                    <label>Password</label>
                    <input <?php if(Data::get('userNotFound') != null) echo "value='".Data::get('userNotFound')->password."'"; ?> name="password" type="password" class="form-control" placeholder="Password" required="Insert your password">
                  </div>
                  <?php 
                    if(Data::get('userNotFound') != null)
                      echo 
                      "<div class='form-group'>".
                        "<div class='alert alert-warning' role='alert'>".
                          Data::get('userNotFound')->errors.
                        "</div>".
                      "</div>";
                  ?>
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>


              </div>
            </div>
          </div>


          <div class="card">
            <div class="card-header" id="headingTwo">
              <h5 class="mb-0">
                <button class="btn btn-light collapsed" data-toggle="collapse" data-target="#collapseRegister" aria-expanded="false" aria-controls="collapseRegister">
                  Register
                </button>
              </h5>
            </div>
            <div id="collapseRegister" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
              <div class="card-body">


                <form action="register/" method="POST">
                  <div class="form-group">
                    <label>Full Name</label>
                    <input name="name" type="text" class="form-control" required="Inset your full name">
                  </div>
                  <div class="form-group">
                    <label>Birthdate</label>
                    <input name="birthdate" type="date" class="form-control">
                  </div>
                  <div class="form-group">
                    <label>Email address</label>
                    <input name="email" type="email" class="form-control" placeholder="Enter email" required="Insert your email">
                    <small id="emailHelp" class="form-text text-muted">Ex: example@gmail.com</small>
                  </div>
                  <div class="form-group">
                    <label>Username</label>
                    <input name="username" type="text" class="form-control">
                  </div>
                  <div class="form-group">
                    <label>Password</label>
                    <input name="password" type="password" class="form-control" placeholder="Password" required="Insert you password">
                  </div>
                  <div class="form-group">
                    <label>Password Confirmation</label>
                    <input name="passwordConfirmation" type="password" class="form-control" placeholder="Password" required="Confirm your password">
                  </div>
                  <button type="submit" class="btn btn-primary">Register</button>
                </form>


              </div>
            </div>
          </div>
        </div>
      


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>