<!DOCTYPE html>
<html>
<head>
	<?php 
		use ArmoredCore\WebObjects\Asset;
		use ArmoredCore\WebObjects\Layout; 
	?>
	<title>Admin Panel</title>
	   <link rel="stylesheet" href="<?= Asset::css('/bootstrap/bootstrap.min.css')?>" media="screen" >
</head>
<body>
<div id="divTable">
</div>
</body>
 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="<?= Asset::js('/changeActiveNavLink.js')?>"></script>
    <script src="<?= Asset::js('/bootstrap/bootstrap.bundle.min.js')?>"></script> 
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
	$(document).ready(function(){		
	    $.ajax({url: "backoffice/data", type: 'post', data:{table:'true'}, success: function(result){
	        	$("#divTable").html(result); 
	    }});
	});
	$(document).on('click', '.block', function(){ 
    	if(confirm("Are you sure you wish to block this user?")){
    		var id= $(this).attr('id');
    		$(document).ready(function(){		
	    		$.ajax({url: "backoffice/data", type: 'post', data:{block:id}, success: function(result){
	        	$("#divTable").html(result); 
	    }});
	});
    	}
	});
	$(document).on('click', '.unblock', function(){ 
    	if(confirm("Are you sure you wish to unblock this user?")){
    		var id= $(this).attr('id');
    		$(document).ready(function(){		
	    		$.ajax({url: "backoffice/data", type: 'post', data:{unblock:id}, success: function(result){
	        	$("#divTable").html(result); 
	    }});
	});
    	}
	}); 
</script>
</html>